services:
  mysql:
    image: mysql:8.4
    container_name: chefcourier-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: RootPassword123
      MYSQL_DATABASE: chefcourier_db
      MYSQL_USER: chefcourier_app
      MYSQL_PASSWORD: ChefCourier@123

    ports:
      - "3306:3306"

    volumes:
      - chefcourier_mysql_data:/var/lib/mysql

volumes:
  chefcourier_mysql_data:
